services:
  mysql:
    container_name: 'guide-mysql'
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=kanban_db'
      - 'MYSQL_PASSWORD=kanban_password'
      - 'MYSQL_ROOT_PASSWORD=root_password123'
      - 'MYSQL_USER=kanban_user'
    ports:
      - '3306:3306'
